# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedpassword',
            name='site',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
